apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: elemental
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
      - name: root
        passwd: "pass"J
      # runcmd:
      # - mkdir -p /usr/local/data
      # - mount /dev/disk/by-label/EXTRA_PART /usr/local/data
    elemental:
      install:
        reboot: true
        device: /dev/sda
        debug: true
        config-dir: /etc/elemental
        #config-url: "/overlay/oem/lvm_volumes_in_fstab.yaml"
  machineInventoryLabels:
    env: "dev"
