apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: elemental
  namespace: fleet-default
spec:
  baseImage: registry.opensuse.org/isv/rancher/elemental/staging/teal53/15.4/rancher/elemental-teal-iso/5.3:latest
  cloud-config:
    write_files:
      - content: |
          install:
            extra-partitions:
              - size: 1024
                fs_type: linux-swap
                label: EXTRA_PART
        path: /etc/elemental/config.yaml
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: elemental
    namespace: fleet-default
